### ISSUE TITLE
make "Install Tomcat Service" tasks opt-out

### ISSUE THREAD

**Issue by jansepke** [ChristopherDavenport/ansible-role-universal-tomcat#31]
would it be possible to add a variable so that one can decide to not create a init or systemd service file?

**Comment by ChristopherDavenport** [comment]
It should be quite simple. Not sure if I'll have time for a little bit.

If you want to hammer it, it should be dropping it into defaults and then attaching the conditional to the [following tasks.](https://github.com/ChristopherDavenport/ansible-role-universal-tomcat/blob/master/tasks/main.yml#L196-L207)

Would love a PR
